"""Создание таблицы обьявление

Revision ID: 87ffd21c7541
Revises: 1566b5a95689
Create Date: 2026-04-15 21:39:30.578110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87ffd21c7541'
down_revision: Union[str, Sequence[str], None] = '1566b5a95689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spatial_ref_sys')
    op.drop_table('pathdeclaration')
    op.drop_index(op.f('idx_usermodel_residence'), table_name='usermodel', postgresql_using='gist')
    op.drop_table('usermodel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usermodel',
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('residence', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password_repeat', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('usermodel_pkey'))
    )
    op.create_index(op.f('idx_usermodel_residence'), 'usermodel', ['residence'], unique=False, postgresql_using='gist')
    op.create_table('pathdeclaration',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name_driver', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('number_phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path_start', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path_end', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('car', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('number_of_passengers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('space_in_the_car', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pathdeclaration_pkey'))
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
